# Generated by Django 6.0.3 on 2026-04-12 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])])),
                ('extracted_text', models.TextField(blank=True)),
                ('analysis_score', models.PositiveIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('matched_skills', models.TextField(blank=True)),
                ('missing_skills', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='core.studentprofile')),
            ],
        ),
    ]
